# Generated by Django 5.1.5 on 2025-01-27 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_type', models.CharField(choices=[('new', 'New Permit'), ('renewal', 'Renewal'), ('amendment', 'Amendment'), ('closure', 'Business Closure')], max_length=20)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('requires_revision', 'Requires Revision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('payment_mode', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi-Annually'), ('quarterly', 'Quarterly')], max_length=20)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('single', 'Single Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('opc', 'One Person Corporation')], max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('business_address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('line_of_business', models.CharField(max_length=100)),
                ('business_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('capitalization', models.DecimalField(decimal_places=2, max_digits=15)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_address', models.TextField()),
                ('owner_telephone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('gross_sales_receipts', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_essential', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_non_essential', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_revisions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_revisions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.businessapplication')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.businessapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_deadline', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.businessapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('submit', 'Submitted'), ('review', 'Reviewed'), ('revise', 'Revision Requested'), ('approve', 'Approved'), ('reject', 'Rejected'), ('payment', 'Payment'), ('comment', 'Comment Added')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.businessapplication')),
            ],
            options={
                'verbose_name_plural': 'Application activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['application_number'], name='application_applica_c16c16_idx'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['tracking_number'], name='application_trackin_539463_idx'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['status'], name='application_status_eca2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='businessapplication',
            index=models.Index(fields=['business_name'], name='application_busines_c65138_idx'),
        ),
    ]
