# Generated by Django 5.1.5 on 2025-01-25 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('new', 'New Permit'), ('renewal', 'Renewal'), ('amendment', 'Amendment'), ('closure', 'Business Closure')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('requires_revision', 'Requires Revision'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('payment_mode', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi-Annually'), ('quarterly', 'Quarterly')], max_length=20)),
                ('registration_number', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('business_type', models.CharField(choices=[('single', 'Single'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('opc', 'One Person Corporation')], max_length=20)),
                ('business_name', models.CharField(max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_address', models.TextField()),
                ('owner_postal_code', models.CharField(max_length=10)),
                ('line_of_business', models.CharField(max_length=100)),
                ('number_of_units', models.IntegerField()),
                ('business_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capitalization', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_mobile', models.CharField(max_length=20)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.businessapplication')),
            ],
        ),
    ]
