# Generated by Django 5.1.5 on 2025-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrequirement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='requirements/%Y/%m/%d/'),
        ),
    ]
