# Generated by Django 5.1.5 on 2025-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationrequirement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapplication',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='closure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessapplication',
            name='previous_permit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='business_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='business_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('opc', 'One Person Corporation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='capitalization',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='line_of_business',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='owner_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessapplication',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
