# Generated by Django 5.1.5 on 2025-04-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_convert_uuid_fields'),
    ]

    operations = [
    ]
