# Generated by Django 5.1.5 on 2025-03-14 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_businessapplication_is_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('avg_wait_time_payment', models.PositiveIntegerField(default=0)),
                ('avg_wait_time_release', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_payment', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_release', models.PositiveIntegerField(default=0)),
                ('peak_hours_start', models.TimeField(blank=True, null=True)),
                ('peak_hours_end', models.TimeField(blank=True, null=True)),
                ('total_served', models.PositiveIntegerField(default=0)),
                ('total_no_shows', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QueueAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('payment', 'Payment Processing'), ('release', 'Permit Release')], max_length=20)),
                ('queue_number', models.CharField(blank=True, max_length=10)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('checked_in', models.BooleanField(default=False)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_duration', models.PositiveIntegerField(default=15)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='applications.businessapplication')),
            ],
            options={
                'ordering': ['slot_date', 'slot_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.CharField(max_length=10)),
                ('counter_type', models.CharField(choices=[('payment', 'Payment Processing'), ('release', 'Permit Release')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_counter', to='queuing.queueappointment')),
            ],
        ),
        migrations.CreateModel(
            name='QueueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('max_appointments', models.IntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
