# Generated by Django 5.1.5 on 2025-04-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_password_changed_at'),
    ]

    operations = [
    ]
