# Generated by Django 5.1.5 on 2025-04-02 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250401_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
