# Generated by Django 5.1.5 on 2025-04-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
    ]
