# Generated by Django 5.1.5 on 2025-02-20 14:01

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationrequirement_document'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('upload', 'Upload'), ('verify', 'Verify'), ('reject', 'Reject'), ('delete', 'Delete'), ('view', 'View')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Document activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_authentic', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('verification_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='document',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='fraud_flags',
        ),
        migrations.RemoveField(
            model_name='document',
            name='fraud_score',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='validation_results',
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='document.pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('dti_registration', 'DTI Registration'), ('business_permit', 'Business Permit'), ('valid_id', 'Valid ID'), ('lease_contract', 'Lease Contract'), ('sanitary_permit', 'Sanitary Permit'), ('fire_safety', 'Fire Safety Permit'), ('barangay_clearance', 'Barangay Clearance'), ('zoning_clearance', 'Zoning Clearance'), ('tax_declaration', 'Tax Declaration'), ('other', 'Other Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application', 'document_type'], name='documents_d_applica_3606ea_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['verification_status'], name='documents_d_verific_9ea278_idx'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentverificationresult',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
