# Generated by Django 5.1.5 on 2025-02-23 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentactivity_documentverificationresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='quarantine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='quarantine_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='quarantine_reason',
            field=models.CharField(blank=True, choices=[('tampering', 'Signs of Tampering'), ('low_quality', 'Low Quality'), ('suspicious_noise', 'Suspicious Noise Patterns'), ('resolution', 'Poor Resolution'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined')], default='pending', max_length=20),
        ),
    ]
