# Generated by Django 5.1.5 on 2025-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_quarantined_document_quarantine_date_and_more'),
    ]

    operations = [
    ]
