# Generated by Django 5.1.5 on 2025-04-01 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_businessapplication_is_released_and_more'),
        ('documents', '0004_auto_20250329_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('fraud_areas', models.JSONField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentactivity',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentactivity',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='documentverificationresult',
            name='document',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_applica_3606ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_verific_9ea278_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_quarantined',
        ),
        migrations.RemoveField(
            model_name='document',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quarantine_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quarantine_notes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quarantine_reason',
        ),
        migrations.RemoveField(
            model_name='document',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='released_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verification_remarks',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='verification_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.businessapplication'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('dti_sec', 'DTI/SEC Registration'), ('lease', 'Contract of Lease'), ('title', 'Transfer Certificate of Title'), ('consent', 'Notarized Consent'), ('signage', 'Picture with Signage'), ('fire_cert', 'Fire Safety Inspection Certificate'), ('zoning', 'Zoning Clearance'), ('hoa', 'HOA Permit'), ('occupancy', 'Occupancy Permit'), ('sanitary', 'Sanitary Permit'), ('barangay', 'Barangay Clearance'), ('gross_receipt', 'Proof of Annual Gross Receipts'), ('sale_deed', 'Deed of Absolute Sale'), ('transfer', 'Deed of Assignment/Transfer of Rights'), ('closure', 'Affidavit of Closure'), ('board_resolution', 'Board Resolution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('fraud', 'Potential Fraud Detected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='documents.document'),
        ),
        migrations.DeleteModel(
            name='DocumentActivity',
        ),
        migrations.DeleteModel(
            name='DocumentVerificationResult',
        ),
    ]
